### ISSUE TITLE
UWS_LINUX_57 NodeJS Binding missing

### ISSUE THREAD

**Issue by f3r** [uNetworking/bindings#37]
Hi guys,

I have spent a few days debugging a problem in my production application. It is a node js application that uses UWS ([https://github.com/hackmdio/hackmd](https://github.com/hackmdio/hackmd)). The problem was every time I deployed to heroku, my application wouldn't start and gave me the following error message:

```
error 2017-07-03T10:19:48.878Z - error: uncaughtException: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'. 
cwd=/app, execPath=/app/.heroku/node/bin/node, 
version=v8.1.3, argv=[/app/.heroku/node/bin/node, /app/app.js], 
stack=[
  Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.,     
  at native (/app/node_modules/uws/uws.js:37:19),     
  at Object.<anonymous> (/app/node_modules/uws/uws.js:41:3),     
  at Module._compile (module.js:569:30),     
  at Object.Module._extensions..js (module.js:580:10),     
  at Module.load (module.js:503:32),     
  at tryModuleLoad (module.js:466:12),     
  at Function.Module._load (module.js:458:3),     
  at Module.require (module.js:513:17),     
  at require (internal/module.js:11:18),     
  at Object.<anonymous> (/app/app.js:77:21),     
  at Module._compile (module.js:569:30),     
  at Object.Module._extensions..js (module.js:580:10),     
  at Module.load (module.js:503:32),     
  at tryModuleLoad (module.js:466:12),     
  at Function.Module._load (module.js:458:3),     
  at Function.Module.runMain (module.js:605:10)]
```

The error was in [this line](https://github.com/uNetworking/bindings/blob/master/nodejs/src/uws.js#L27):

```
const native = (() => {
    try {
        try {
            return process.binding('uws_builtin');
        } catch (e) {
            return require(`./uws_${process.platform}_${process.versions.modules}`);
        }
    } catch (e) {
        const version = process.version.substring(1).split('.').map(function(n) {
            return parseInt(n);
        });
```

and it had to do with requiring the UWS module. Heroku, in it's latest [Cedar-16 Stack](https://devcenter.heroku.com/articles/heroku-16-stack) uses `node v8.1.3`, and `process.versions.modules` is **57**, but it doesn't seem you guys have a binary file for `uws_linux_57`:

```
$ ls -1 node_modules/uws/uws_*.node
uws_darwin_46.node
uws_darwin_47.node
uws_darwin_48.node
uws_darwin_51.node
uws_linux_46.node
uws_linux_47.node
uws_linux_48.node
uws_linux_51.node
uws_win32_48.node
uws_win32_51.node
```

Would it be possible to generate `uws_linux_57`?

Thanks in advance!

**Comment by alexhultman** [comment]
8.14.0 has said linux binary.
