### ISSUE TITLE
Add binaries for Solaris - nodejs

### ISSUE THREAD

**Issue by usebaz** [uNetworking/bindings#74]
Hello,
Can you add binaries for Solaris?
Because build from sources failed on sunos.

**build_log.txt:**
```
make: Entering directory `/opt/services/wss-webapp/node_modules/uws/build'
  CXX(target) Release/obj.target/uws/src/Extensions.o
  CXX(target) Release/obj.target/uws/src/Group.o
In file included from ../src/WebSocket.h:4:0,
                 from ../src/Group.h:4,
                 from ../src/Group.cpp:1:
../src/WebSocketProtocol.h: In static member function 'static std::size_t uWS::WebSocketProtocol<isServer, Impl>::formatMessage(char*, const char*, std::size_t, uWS::OpCode, std::size_t, bool)':
../src/WebSocketProtocol.h:292:61: error: there are no arguments to 'htobe64' that depend on a template parameter, so a declaration of 'htobe64' must be available [-fpermissive]
             *((uint64_t *) &dst[2]) = htobe64(reportedLength);
                                                             ^
../src/WebSocketProtocol.h:292:61: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
../src/WebSocketProtocol.h: In static member function 'static void uWS::WebSocketProtocol<isServer, Impl>::consume(char*, unsigned int, uWS::WebSocketState<isServer>*)':
../src/WebSocketProtocol.h:358:103: error: there are no arguments to 'be64toh' that depend on a template parameter, so a declaration of 'be64toh' must be available [-fpermissive]
                 } else if (consumeMessage<LONG_MESSAGE_HEADER, uint64_t>(be64toh(*(uint64_t *) &src[2]), src, length, wState)) {
                                                                                                       ^
In file included from ../src/Hub.h:5:0,
                 from ../src/Group.cpp:2:
../src/Node.h: In member function 'uS::Socket* uS::Node::connect(const char*, int, bool, uS::NodeData*)':
../src/Node.h:96:35: error: 'to_string' is not a member of 'std'
         if (getaddrinfo(hostname, std::to_string(port).c_str(), &hints, &result) != 0) {
                                   ^
../src/Node.h: In member function 'bool uS::Node::listen(const char*, int, uS::TLS::Context, int, uS::NodeData*, void*)':
../src/Node.h:136:31: error: 'to_string' is not a member of 'std'
         if (getaddrinfo(host, std::to_string(port).c_str(), &hints, &result)) {
                               ^
In file included from ../src/Group.cpp:2:0:
../src/Hub.h: At global scope:
../src/Hub.h:21:33: warning: missing initializer for member 'z_stream_s::next_in' [-Wmissing-field-initializers]
     z_stream inflationStream = {};

../src/Hub.h:21:33: warning: missing initializer for member 'z_stream_s::avail_in' [-Wmissing-field-initializers]
../src/Hub.h:21:33: warning: missing initializer for member 'z_stream_s::total_in' [-Wmissing-field-initializers]
../src/Hub.h:21:33: warning: missing initializer for member 'z_stream_s::next_out' [-Wmissing-field-initializers]
../src/Hub.h:21:33: warning: missing initializer for member 'z_stream_s::avail_out' [-Wmissing-field-initializers]
../src/Hub.h:21:33: warning: missing initializer for member 'z_stream_s::total_out' [-Wmissing-field-initializers]
../src/Hub.h:21:33: warning: missing initializer for member 'z_stream_s::msg' [-Wmissing-field-initializers]
../src/Hub.h:21:33: warning: missing initializer for member 'z_stream_s::state' [-Wmissing-field-initializers]
../src/Hub.h:21:33: warning: missing initializer for member 'z_stream_s::zalloc' [-Wmissing-field-initializers]
../src/Hub.h:21:33: warning: missing initializer for member 'z_stream_s::zfree' [-Wmissing-field-initializers]
../src/Hub.h:21:33: warning: missing initializer for member 'z_stream_s::opaque' [-Wmissing-field-initializers]
../src/Hub.h:21:33: warning: missing initializer for member 'z_stream_s::data_type' [-Wmissing-field-initializers]
../src/Hub.h:21:33: warning: missing initializer for member 'z_stream_s::adler' [-Wmissing-field-initializers]
../src/Hub.h:21:33: warning: missing initializer for member 'z_stream_s::reserved' [-Wmissing-field-initializers]
make: *** [Release/obj.target/uws/src/Group.o] Error 1
make: Leaving directory `/opt/services/wss-webapp/node_modules/uws/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/node8/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System SunOS 5.11
gyp ERR! command "/usr/node8/bin/node" "/usr/node8/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/services/wss-webapp/node_modules/uws
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

**Comment by usebaz** [comment]
@alexhultman @szmoore @lauriro

**Comment by alexhultman** [comment]
That's unfortunate, a missing header it seems, but there is no plan to support Solaris if it doesn't already work.

**Comment by usebaz** [comment]
@alexhultman 
For our projects, we have compiled a binary package. We can support if needed.
